

import { FC } from 'react' ;
import Head from 'next/head' ;
import { 
         Basic_Header , 
         Top_Cards ,
         Bar_Chart ,
         Admin_Header ,
       } from '@layout/index';

import { Today_Appointment , Shop_Status } from "@service/index"


const Index_Dashboard_Controller : FC = () => {


    return <>
    
             <Head>
                <title> 後台管理系統 </title>
                <meta name = "description" content = "Generated by create next app" />
                <meta name = "viewport" content = "width=device-width , initial-scale=1" />
                <link rel = "icon" href="/favicon.ico" />
             </Head>

             <main className = 'bg-gray-100 min-h-screen' >

                <Admin_Header />

                {/* <Top_Cards /> */}

                <div className="p-2 grid md:grid-cols-5 grid-cols-1 gap-2 h-[85vh]">

                  { /* 今日預約 */ }
                  <Today_Appointment />

                  { /* 到店處理狀態 */ }
                  <Shop_Status />
                  
                </div>
            
             </main>

           </>

} ;


export default Index_Dashboard_Controller
       